d1to9 =: 'one','two','three','four','five','six','seven','eight','nine'
d10to19 =: 'ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen'
d20to90 =: 'twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety'
d100 =: 'hundred'
d1000 =: 'thousand'
